version: "3.9"
services:
  redis:
    image: "bitnami/redis:7.0"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis/data

  websocket-service-1:
    build: .
    image: "romanowalex/websocket-service:v1.0"
    container_name: "websocket-service-1"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    depends_on:
      - redis

  websocket-service-2:
    build: .
    image: "romanowalex/websocket-service:v1.0"
    container_name: "websocket-service-2"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    depends_on:
      - redis

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - websocket-service-1
      - websocket-service-2

volumes:
  redis-data: