version: "3.9"
services:
  websocket-service:
    build: .
    image: romanowalex/websocket-service:v1.0
    container_name: websocket-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"