spring:
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce

artemis:
  host: localhost
  port: 61616

logging.level:
  org.springframework.messaging: debug
  org.springframework.web.socket.server: debug
  org.springframework.security: debug
